baseURL: "https://satwatbashir.com/"

title: Satwat Bashir
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
paginate: 20
relativeURLs: true



taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Design
          url: /design/
          weight: 3        
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archive/
          weight: 5

params:
    description: "This website hosts satwat bashir research papers, course materials, design templates, curriculum vitae, and contact information."
    author: satwat
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","teaching","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    extraCSS: |
      body {
        background-color: black;
        color: white;
      }

    profileMode:
          enabled: true
          title: Satwat Bashir
          subtitle: " I am a PhD student in Computer Science at London South Bank University (LSBU).  My research focuses primarily on heterogeneity in federated learning and how it impacts convergence and accuracy in edge-cloud environments. I explore challenges in data, model and devices to better understand and improve decentralized systems."
          imageUrl: "/satwat.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Papers
              url:  https://scholar.google.com/citations?hl=en&user=Hlwom6QAAAAJ
            - name: Teaching
              url:  https://scholar.google.com/citations?hl=en&user=Hlwom6QAAAAJ


    socialIcons:
        - name: CV
          url: /Satwat-CV.pdf
        - name: Email
          url: mailto:bashis11@lsbu.ac.uk
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=Hlwom6QAAAAJ
        - name: GitHub
          url: https://github.com/satwatbashir
        - name: LinkedIn
          url: https://www.linkedin.com/in/satwat/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "satwat bashir"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
